version: '3.4'

services:
  postgresql_database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=MediPlaceDatabase
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./SQL:/docker-entrypoint-initdb.d