version: '3.3'
services:
    mongo:
        ports:
            - '27017:27017'
        restart: unless-stopped
        logging:
            options:
                max-size: 1g
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
        image: mongo:latest